/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimemachineRouteImport } from './routes/timemachine'
import { Route as SongRouteImport } from './routes/song'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewindRouteImport } from './routes/rewind'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProbabilityRouteImport } from './routes/probability'
import { Route as PlaylistRouteImport } from './routes/playlist'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LivequizRouteImport } from './routes/livequiz'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FaceoffRouteImport } from './routes/faceoff'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as IndexRouteImport } from './routes/index'

const TimemachineRoute = TimemachineRouteImport.update({
  id: '/timemachine',
  path: '/timemachine',
  getParentRoute: () => rootRouteImport,
} as any)
const SongRoute = SongRouteImport.update({
  id: '/song',
  path: '/song',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewindRoute = RewindRouteImport.update({
  id: '/rewind',
  path: '/rewind',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbabilityRoute = ProbabilityRouteImport.update({
  id: '/probability',
  path: '/probability',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LivequizRoute = LivequizRouteImport.update({
  id: '/livequiz',
  path: '/livequiz',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceoffRoute = FaceoffRouteImport.update({
  id: '/faceoff',
  path: '/faceoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/explore': typeof ExploreRoute
  '/faceoff': typeof FaceoffRoute
  '/home': typeof HomeRoute
  '/livequiz': typeof LivequizRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/playlist': typeof PlaylistRoute
  '/probability': typeof ProbabilityRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/rewind': typeof RewindRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/song': typeof SongRoute
  '/timemachine': typeof TimemachineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/explore': typeof ExploreRoute
  '/faceoff': typeof FaceoffRoute
  '/home': typeof HomeRoute
  '/livequiz': typeof LivequizRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/playlist': typeof PlaylistRoute
  '/probability': typeof ProbabilityRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/rewind': typeof RewindRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/song': typeof SongRoute
  '/timemachine': typeof TimemachineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/explore': typeof ExploreRoute
  '/faceoff': typeof FaceoffRoute
  '/home': typeof HomeRoute
  '/livequiz': typeof LivequizRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/playlist': typeof PlaylistRoute
  '/probability': typeof ProbabilityRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/rewind': typeof RewindRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/song': typeof SongRoute
  '/timemachine': typeof TimemachineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battle'
    | '/explore'
    | '/faceoff'
    | '/home'
    | '/livequiz'
    | '/login'
    | '/notifications'
    | '/playlist'
    | '/probability'
    | '/profile'
    | '/quiz'
    | '/rewind'
    | '/settings'
    | '/signup'
    | '/song'
    | '/timemachine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/battle'
    | '/explore'
    | '/faceoff'
    | '/home'
    | '/livequiz'
    | '/login'
    | '/notifications'
    | '/playlist'
    | '/probability'
    | '/profile'
    | '/quiz'
    | '/rewind'
    | '/settings'
    | '/signup'
    | '/song'
    | '/timemachine'
  id:
    | '__root__'
    | '/'
    | '/battle'
    | '/explore'
    | '/faceoff'
    | '/home'
    | '/livequiz'
    | '/login'
    | '/notifications'
    | '/playlist'
    | '/probability'
    | '/profile'
    | '/quiz'
    | '/rewind'
    | '/settings'
    | '/signup'
    | '/song'
    | '/timemachine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleRoute: typeof BattleRoute
  ExploreRoute: typeof ExploreRoute
  FaceoffRoute: typeof FaceoffRoute
  HomeRoute: typeof HomeRoute
  LivequizRoute: typeof LivequizRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PlaylistRoute: typeof PlaylistRoute
  ProbabilityRoute: typeof ProbabilityRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  RewindRoute: typeof RewindRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SongRoute: typeof SongRoute
  TimemachineRoute: typeof TimemachineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timemachine': {
      id: '/timemachine'
      path: '/timemachine'
      fullPath: '/timemachine'
      preLoaderRoute: typeof TimemachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song': {
      id: '/song'
      path: '/song'
      fullPath: '/song'
      preLoaderRoute: typeof SongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewind': {
      id: '/rewind'
      path: '/rewind'
      fullPath: '/rewind'
      preLoaderRoute: typeof RewindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probability': {
      id: '/probability'
      path: '/probability'
      fullPath: '/probability'
      preLoaderRoute: typeof ProbabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livequiz': {
      id: '/livequiz'
      path: '/livequiz'
      fullPath: '/livequiz'
      preLoaderRoute: typeof LivequizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faceoff': {
      id: '/faceoff'
      path: '/faceoff'
      fullPath: '/faceoff'
      preLoaderRoute: typeof FaceoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleRoute: BattleRoute,
  ExploreRoute: ExploreRoute,
  FaceoffRoute: FaceoffRoute,
  HomeRoute: HomeRoute,
  LivequizRoute: LivequizRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PlaylistRoute: PlaylistRoute,
  ProbabilityRoute: ProbabilityRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  RewindRoute: RewindRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SongRoute: SongRoute,
  TimemachineRoute: TimemachineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
